package cli

import (
	"fmt"
	"os"

	"github.com/alapierre/bb-insights/internal/parser/coverage"
)

// CoverageCmd implements "publish coverage".
type CoverageCmd struct {
	Globals

	Input string `required:"" type:"existingfile" name:"input" env:"BB_INSIGHTS_INPUT" help:"Path to the coverage.out profile generated by 'go test -coverprofile'."`
}

func (c *CoverageCmd) Run() error {
	f, err := os.Open(c.Input)
	if err != nil {
		return fmt.Errorf("cli: opening coverage profile %q: %w", c.Input, err)
	}
	defer f.Close()

	report, err := coverage.Parse(f)
	if err != nil {
		return err
	}

	return c.publish(report)
}
