package cli

import (
	"fmt"
	"os"

	"github.com/alapierre/bb-insights/internal/parser/junit"
)

// TestsCmd implements "publish tests".
type TestsCmd struct {
	Globals

	JUnit string `required:"" type:"existingfile" name:"junit" env:"BB_INSIGHTS_JUNIT" help:"Path to the JUnit XML report generated by gotestsum."`
}

func (c *TestsCmd) Run() error {
	f, err := os.Open(c.JUnit)
	if err != nil {
		return fmt.Errorf("cli: opening JUnit report %q: %w", c.JUnit, err)
	}
	defer func() { _ = f.Close() }()

	report, err := junit.Parse(f)
	if err != nil {
		return err
	}

	return c.publish(report)
}
